name: Sync Discovered API with ApiConnect

on: [pull_request, workflow_dispatch, push]

env:
  API_HOST: d-j02.apiconnect.dev.automation.ibm.com
  PROVIDER_ORG: niraimathi
  API_FILES: gmail-api.yaml,mit-api.json

jobs:
  get_changed_file:
    runs-on: ubuntu-latest
    outputs:
      changed_filename: ${{ steps.changed_filename.api_file }}
      apifiles_env: ${{ steps.changed_filename.apifiles_env }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Changed API File Name
        id: changed_filename
        run: |
          echo "api_file=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep "" | xargs)" >> $GITHUB_OUTPUT
          echo "apifiles_env=$(echo $API_FILES)" >> $GITHUB_OUTPUT
          echo "Entered"
          echo "${{ steps.changed_filename.api_file }}"
          echo "${{ steps.changed_filename.apifiles_env }}"
  check_apifiles_job:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      action_changed: ${{ steps.check_apifiles_changed.outputs.action_updates }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Check API File changed
      id: check_apifiles_changed
      run: |
        echo "action_updates=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.before }} ${{ github.sha }} | grep discover-api.yml | xargs)" >> $GITHUB_OUTPUT
        echo "Check here"
  run-discovery:
    runs-on: ubuntu-latest
    needs: [ check_apifiles_job, get_changed_file ]
    if: ${{ (contains(needs.get_changed_file.outputs.apifiles_env,needs.get_changed_file.outputs.changed_filename)) || (needs.check_apifiles_job.outputs.action_changed) }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruairi-hayes/apic-discovery-action@ng/main
      id: discover-apis
      with:
        api_host: ${{ env.API_HOST }}
        provider_org: ${{ env.PROVIDER_ORG }}
        api_key: ${{ secrets.apicApikey }}
        api_files: ${{ env.API_FILES }}
        resync_check: ${{ needs.check_apifiles_job.outputs.action_changed && true || false }}
    - name: Display the action-result
      run: |
        echo "Result of the action: ${{ steps.discover-apis.outputs.action-result }}"
